Switch from SVN to Git for ports repo.
Closes #3.

diff --git a/portsfetch b/portsfetch
--- a/portsfetch
+++ b/portsfetch
@@ -2,15 +2,23 @@
 
 :<<DOCUMENTATION
 
-	Description:	Updates the local ports tree from the current quarterly SVN branch.
+	Description:	Updates the local ports tree from the current quarterly Git branch.
 	Author:			Chris Wells (https://chriswells.io)
 
 DOCUMENTATION
 
 
-# Modify these variables if you use a different SVN branch or repo. -- cwells
-BRANCH=$(svnlite ls https://svn.freebsd.org/ports/branches/ | sed -ne '/^20[0-9]\{2\}Q[1-4]/s|/$||p' | tail -1)
-URL="https://svn.freebsd.org/ports/branches/$BRANCH"
+REPO_URL="https://git.freebsd.org/ports.git"
+
+# Require root in order to write to the ports dir. -- cwells
+if [ "$(id -u)" != "0" ]; then
+	echo 'This script must be run as root or using sudo.' 1>&2
+	exit 1
+fi
+
+if ! which git > /dev/null; then
+	pkg install git
+fi
 
 # If a parameter was passed, use it as the destination directory.  For example,
 # to update the ezjail ports tree: portsfetch /usr/jails/basejail/usr/ports
@@ -20,45 +28,41 @@ else
 	DESTDIR=/usr/ports
 fi
 
-# Require root in order to write to the ports dir. -- cwells
-if [ "$(id -u)" != "0" ]; then
-	echo 'This script must be run as root or using sudo.' 1>&2
-	exit 1
+if [ ! -d "${DESTDIR}" ]; then
+	mkdir "${DESTDIR}"
 fi
 
-# Validate variables before proceeding. -- cwells
-if [ ! -d "$DESTDIR" ]; then
-	echo 'Destination directory not found.'
-	exit 1
-elif [ "${#BRANCH}" != "6" ]; then
-	echo 'Failed to determine the correct branch to use.'
-	exit 1
-fi
-
-# Clear the contents of the destination directory if it's not being managed by SVN. -- cwells
-if [ ! -z "$(ls -qAL -- "$DESTDIR")" ] && [ ! -d "$DESTDIR/.svn" ]; then
-	echo 'Destination directory contains files but is not an SVN branch.'
+# Clear the contents of the destination directory if it's not being managed by Git. -- cwells
+if [ ! -z "$(ls -qAL -- "${DESTDIR}")" ] && [ ! -d "${DESTDIR}/.git" ]; then
+	echo 'Destination directory contains files but is not a Git repo.'
 	echo 'You must delete the existing files to switch to a quarterly branch.'
 	# shellcheck disable=SC2039
-	read -r -p "Do you want to delete the contents of \"$DESTDIR\"? [y/N]: " DELETE_FILES
+	read -r -p "Do you want to delete the contents of \"${DESTDIR}\"? [y/N]: " DELETE_FILES
 	case $DELETE_FILES in
-		[Yy]* ) find "$DESTDIR" -mindepth 1 -delete ;; # Delete all files in the dir. -- cwells
+		[Yy]* ) find "${DESTDIR}" -mindepth 1 -delete ;; # Delete all files in the dir. -- cwells
 		* ) portsnap fetch update; exit 0 ;; # Use portsnap to update from HEAD. -- cwells
 	esac
 	echo ''
 fi
 
-if [ -d "$DESTDIR/.svn" ]; then # Destination directory is already managed by SVN. -- cwells
-	if [ "$(svnlite info "$DESTDIR" | sed -ne 's/^URL: \(.*\)$/\1/p')" = "$URL" ]; then # Just update. -- cwells
-		svnlite update "$DESTDIR"
-	else # Switch to the current quarterly branch. -- cwells
-		echo "Switching to the $BRANCH branch..."
-		svnlite switch "$URL" "$DESTDIR"
-	fi
-else # Perform a fresh checkout of the current quarterly branch. -- cwells
-	echo "Checking out a fresh copy of the $BRANCH branch..."
-	svnlite checkout "$URL" "$DESTDIR"
+FRESH_CLONE=false
+if [ ! -d "${DESTDIR}/.git" ]; then # Initial clone of the repo. -- cwells
+	git clone "${REPO_URL}" "${DESTDIR}"
+	FRESH_CLONE=true
 fi
 
+BRANCH=$(git -C "${DESTDIR}" branch --list -r | grep -E '^\s*origin/20[0-9]{2}Q[1-4]$' | sort | tail -1 | sed 's/ *origin\///')
+if [ "${#BRANCH}" != "6" ]; then
+	echo 'Failed to determine the correct branch to use.'
+	exit 1
+fi
+
+if [ "$(git -C "${DESTDIR}" branch --show-current)" != "${BRANCH}" ]; then
+	git -C "${DESTDIR}" checkout "${BRANCH}"
+fi
+
+if [ "${FRESH_CLONE}" = 'false' ]; then
+	git -C "${DESTDIR}" pull --ff-only
+fi
 
 exit 0
